import { Link, useLocation } from "react-router-dom";
import { Sparkles, Globe, Shield, Brain, Zap, BookOpen, ChevronRight, Building2, User, FileText } from "lucide-react";
import { PageShell } from "@/components/PageShell";
import { SEO } from "@/components/SEO";
import { detectLangFromPath, localizePath } from "@/i18n/routing";

const PILLARS = [
  {
    icon: Brain,
    label: "AI-assisted intelligence",
    body: "Our recommendations combine public data, manufacturer specifications, reviewer consensus and AI-assisted pattern recognition. Every insight is editorial guidance — not automated replacement for your own judgement.",
    color: "text-violet-400",
    border: "border-violet-500/20",
    tint: "from-violet-500/10 to-violet-500/0",
  },
  {
    icon: Shield,
    label: "Editorial independence",
    body: "AUTOVERE does not accept affiliate commissions, manufacturer fees or sponsored placements. Our analysis reflects what we find in the data, not what someone pays us to say.",
    color: "text-emerald-400",
    border: "border-emerald-500/20",
    tint: "from-emerald-500/10 to-emerald-500/0",
  },
  {
    icon: Globe,
    label: "European by design",
    body: "Coverage is built around European automotive reality — WLTP range cycles, local charging infrastructure, country-level incentives, and the winters that demand honest performance data.",
    color: "text-cyan-400",
    border: "border-cyan-500/20",
    tint: "from-cyan-500/10 to-cyan-500/0",
  },
  {
    icon: Zap,
    label: "EV-forward ownership data",
    body: "As electrification accelerates, intelligent EV guidance becomes more valuable. We go beyond manufacturer brochures — real-world range, charging network honesty, winter performance and total ownership economics.",
    color: "text-amber-400",
    border: "border-amber-500/20",
    tint: "from-amber-500/10 to-amber-500/0",
  },
  {
    icon: BookOpen,
    label: "Transparency by default",
    body: "Data sources are labelled. AI involvement is disclosed. Ownership projections are estimates. Pricing varies by region. We say these things clearly — because trust starts with honesty about limitations.",
    color: "text-sky-400",
    border: "border-sky-500/20",
    tint: "from-sky-500/10 to-sky-500/0",
  },
  {
    icon: Sparkles,
    label: "Premium craft, not clutter",
    body: "AUTOVERE is deliberately minimal. Premium automotive decisions deserve a calm, considered environment — not another dashboard of noise. The design is a product decision, not decoration.",
    color: "text-pink-400",
    border: "border-pink-500/20",
    tint: "from-pink-500/10 to-pink-500/0",
  },
];

const DATA_NOTES = [
  { label: "Vehicle range", note: "WLTP figures from official manufacturer publications. Real-world estimates sourced from Bjørn Nyland, Out of Spec Reviews, and ADAC." },
  { label: "Ownership costs", note: "Projected 5-year totals are estimates based on typical usage, regional fuel/electricity pricing, and published depreciation patterns. Actual costs vary." },
  { label: "Charging data", note: "Network speeds and coverage represent available public information. Live station availability requires real-time API integration, noted where present." },
  { label: "AI recommendations", note: "Generated by combining structured data with language model reasoning. Not professional purchase advice — verify final details before signing anything." },
  { label: "Media", note: "Images are sourced from OEM press kits, editorial sources or manufacturer press materials. Vehicle names and marks belong to their respective manufacturers, used for editorial purposes." },
  { label: "YouTube content", note: "Embedded reviews come from independent automotive publishers. AUTOVERE curates and analyses these — we are not affiliated with the channels." },
];

export default function About() {
  const { pathname } = useLocation();
  const lang = detectLangFromPath(pathname);
  const L = (p: string) => localizePath(p, lang);

  return (
    <PageShell>
      <SEO
        title="About AUTOVERE - KM TECH LABS, Kristiansand, Norway"
        description="AUTOVERE is a premium European automotive intelligence platform, developed and operated by KM TECH LABS in Kristiansand, Norway. Editorial independence, transparent AI and real-world EV data."
        image="https://autovere.com/og-autovere-1200x630.jpg"
      />

      {/* Hero */}
      <section className="relative bg-hero grid-bg overflow-hidden pt-40 pb-28">
        <div className="absolute inset-0 bg-gradient-to-br from-violet-950/40 via-transparent to-cyan-950/30 pointer-events-none" />
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[640px] h-[640px] rounded-full bg-violet-500/5 blur-3xl pointer-events-none" />
        <div className="container relative max-w-3xl">
          <div className="inline-flex items-center gap-2 text-[11px] font-medium uppercase tracking-[0.25em] text-violet-400 mb-6">
            <Sparkles className="w-3.5 h-3.5" /> AUTOVERE · About
          </div>
          <h1 className="text-5xl md:text-7xl font-bold tracking-tight mb-7">
            Built for the{" "}
            <span className="text-gradient">thoughtful buyer.</span>
          </h1>
          <p className="text-lg md:text-xl text-muted-foreground leading-relaxed mb-10 max-w-2xl">
            AUTOVERE is a European automotive intelligence platform designed to bring clarity, honesty and premium depth
            to one of the most consequential decisions people make — choosing a vehicle.
          </p>
          <div className="flex flex-wrap gap-4">
            <Link
              to={L("/ev")}
              className="inline-flex items-center gap-2 px-6 py-3 rounded-xl bg-gradient-primary text-primary-foreground font-medium hover:opacity-90 transition-opacity"
            >
              Explore the EV layer <ChevronRight className="w-4 h-4" />
            </Link>
            <Link
              to={L("/contact")}
              className="inline-flex items-center gap-2 px-6 py-3 rounded-xl glass border border-border/50 hover:border-border transition-colors"
            >
              Get in touch <ChevronRight className="w-4 h-4" />
            </Link>
          </div>
        </div>
      </section>

      {/* Mission statement */}
      <section className="container py-20 max-w-4xl">
        <div className="glass rounded-3xl border border-border/40 p-10 md:p-14 relative overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-br from-violet-500/5 via-transparent to-cyan-500/5 pointer-events-none" />
          <div className="relative">
            <p className="text-xs uppercase tracking-[0.25em] text-accent mb-5">Mission</p>
            <blockquote className="text-2xl md:text-3xl font-semibold tracking-tight leading-snug text-foreground mb-6">
              "Most automotive platforms optimise for volume. We optimise for confidence. The goal is a single, well-reasoned decision — not 200 filtered listings."
            </blockquote>
            <p className="text-muted-foreground leading-relaxed max-w-2xl">
              AUTOVERE was built because the existing tools don't serve people who think carefully about vehicle ownership.
              We believe that intelligence, clarity and editorial rigour should be the default — not a premium exception.
            </p>
          </div>
        </div>
      </section>

      {/* Editorial pillars */}
      <section className="container pb-20">
        <div className="mb-12">
          <p className="text-xs uppercase tracking-[0.25em] text-accent mb-3">What we stand for</p>
          <h2 className="text-3xl md:text-4xl font-bold tracking-tight max-w-2xl">Six principles that shape every decision.</h2>
        </div>
        <div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-5">
          {PILLARS.map((pillar) => (
            <div
              key={pillar.label}
              className={`glass rounded-3xl border ${pillar.border} bg-gradient-to-br ${pillar.tint} p-7`}
            >
              <div className={`w-10 h-10 rounded-xl bg-card flex items-center justify-center mb-5 ${pillar.color}`}>
                <pillar.icon className="w-5 h-5" />
              </div>
              <h3 className="font-semibold text-lg mb-3">{pillar.label}</h3>
              <p className="text-sm text-muted-foreground leading-relaxed">{pillar.body}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Company identity */}
      <section className="container pb-20">
        <div className="grid lg:grid-cols-2 gap-8">
          <div className="glass rounded-3xl border border-border/40 p-8">
            <div className="flex items-center gap-3 mb-6">
              <div className="w-10 h-10 rounded-xl bg-gradient-primary/20 border border-primary/20 flex items-center justify-center text-primary">
                <Building2 className="w-5 h-5" />
              </div>
              <div>
                <p className="text-xs uppercase tracking-[0.2em] text-muted-foreground mb-0.5">Developer & operator</p>
                <p className="font-semibold text-lg">KM TECH LABS</p>
              </div>
            </div>
            <div className="space-y-3 text-sm text-muted-foreground">
              <div className="flex items-start gap-3">
                <span className="w-24 flex-shrink-0 text-[11px] uppercase tracking-wider text-muted-foreground/60 mt-0.5">Location</span>
                <span>Møviklia 4, 4623 Kristiansand, Norway</span>
              </div>
              <div className="flex items-start gap-3">
                <span className="w-24 flex-shrink-0 text-[11px] uppercase tracking-wider text-muted-foreground/60 mt-0.5">Org. number</span>
                <span>934 044 029</span>
              </div>
              <div className="flex items-start gap-3">
                <span className="w-24 flex-shrink-0 text-[11px] uppercase tracking-wider text-muted-foreground/60 mt-0.5">Country</span>
                <span>Norway · EEA / GDPR jurisdiction</span>
              </div>
            </div>
          </div>

          <div className="glass rounded-3xl border border-border/40 p-8">
            <div className="flex items-center gap-3 mb-6">
              <div className="w-10 h-10 rounded-xl bg-gradient-primary/20 border border-primary/20 flex items-center justify-center text-primary">
                <User className="w-5 h-5" />
              </div>
              <div>
                <p className="text-xs uppercase tracking-[0.2em] text-muted-foreground mb-0.5">Editor-in-chief</p>
                <p className="font-semibold text-lg">Kjell Mersland</p>
              </div>
            </div>
            <p className="text-sm text-muted-foreground leading-relaxed mb-5">
              Kjell Mersland holds editorial responsibility for all content published on AUTOVERE — including vehicle guides, EV analysis, market intelligence and AI-assisted recommendations.
            </p>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Editorial decisions are made independently of commercial relationships. No manufacturer, dealer or partner organisation influences editorial coverage.
            </p>
          </div>
        </div>
      </section>

      {/* Data source transparency */}
      <section className="container pb-20 max-w-4xl">
        <div className="mb-10">
          <p className="text-xs uppercase tracking-[0.25em] text-accent mb-3">Data transparency</p>
          <h2 className="text-3xl font-bold tracking-tight">What our data is, and what it isn't.</h2>
          <p className="text-muted-foreground mt-4 leading-relaxed max-w-xl">
            Automotive data is imperfect. Real-world performance diverges from manufacturer claims. We try to be honest about both.
          </p>
        </div>
        <div className="glass rounded-3xl border border-border/40 divide-y divide-border/30 overflow-hidden">
          {DATA_NOTES.map((item) => (
            <div key={item.label} className="grid md:grid-cols-[200px_1fr] gap-4 px-7 py-5">
              <div className="text-sm font-medium text-foreground pt-0.5">{item.label}</div>
              <p className="text-sm text-muted-foreground leading-relaxed">{item.note}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Legal links CTA */}
      <section className="container pb-28">
        <div className="glass rounded-3xl border border-border/40 p-8 md:p-12 relative overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-br from-cyan-500/5 via-transparent to-violet-500/5 pointer-events-none" />
          <div className="relative grid md:grid-cols-[1fr_auto] gap-8 items-start">
            <div>
              <div className="flex items-center gap-2 mb-4">
                <FileText className="w-4 h-4 text-accent" />
                <span className="text-xs uppercase tracking-[0.25em] text-accent">Legal documents</span>
              </div>
              <h2 className="text-2xl font-bold tracking-tight mb-3">Clarity on paper, not just in conversation.</h2>
              <p className="text-sm text-muted-foreground leading-relaxed max-w-xl">
                Our Terms of Service, Privacy Policy and Subscription Terms are written in plain language. No legalese walls.
                If something is unclear, <Link to={L("/contact")} className="text-accent hover:underline">reach out directly</Link>.
              </p>
            </div>
            <div className="flex flex-col gap-2.5 min-w-[180px]">
              {[
                { to: "/legal/terms", label: "Terms of Service" },
                { to: "/legal/privacy", label: "Privacy Policy" },
                { to: "/legal/subscriptions", label: "Subscription Terms" },
                { to: "/legal/refund", label: "Refund Policy" },
              ].map((item) => (
                <Link
                  key={item.to}
                  to={L(item.to)}
                  className="inline-flex items-center justify-between gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors glass rounded-xl border border-border/30 px-4 py-2.5"
                >
                  {item.label}
                  <ChevronRight className="w-3.5 h-3.5 opacity-50" />
                </Link>
              ))}
            </div>
          </div>
        </div>
      </section>
    </PageShell>
  );
}
